### ISSUE TITLE
什么情况?? 缺动态库?

### ISSUE THREAD

**Issue by hhhaiai** [marlboro3420/UltrasonicDome#1]
Failure [INSTALL_FAILED_MISSING_SHARED_LIBRARY]

**Comment by marlboro3420** [comment]
有没有具体的LOG信息，我还没遇到过这个错误

**Comment by marlboro3420** [comment]
我复现了这个错误，大概是你直接运行到了安卓手机上。这个项目是运行在Android Thing上的，你可以看看使用说明。
